name: 'Setup SSH Action'
description: 'This action setups your SSH key for any host'
author: 'LuisEnMarroquin'
branding:
  color: 'green'
  icon: 'award'
inputs:
  ORIGIN:
    description: 'SSH origin'
    default: 'github.com'
    required: false
  SSHKEY:
    description: 'SSH key'
    required: true
  NAME:
    description: 'SSH host'
    required: false
  PORT:
    description: 'SSH port'
    required: false
  USER:
    description: 'SSH user'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
