name: 'Setup SSH Action'
description: 'This action setups your SSH key for any host'
author: 'LuisEnMarroquin'
branding:
  color: 'green'
  icon: 'key'
inputs:
  ORIGIN:
    description: 'SSH origin'
    default: 'github.com'
    required: false
  SSHKEY:
    description: 'SSH key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
