name: Testing

on:
  push:
    branches:
    - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v1.2
      with:
        ORIGIN: ${{ secrets.HOST }}
        SSHKEY: ${{ secrets.SSH_SERVER }}
        HOST: production
        USER: ${{ secrets.USER }}
    - run: ssh production pwd
  macos:
    runs-on: macos-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v1.2
      with:
        SSHKEY: ${{ secrets.SSH_GITHUB }}
    - run: ssh -T git@github.com || true
  windows:
    runs-on: windows-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v1.2
      with:
        SSHKEY: ${{ secrets.SSH_GITHUB }}
    - run: ssh -T git@github.com || true
