name: Testing

on:
  push:
    branches:
    - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: LuisEnMarroquin/git-login-action@v1.0
      with:
        SSHKEY: ${{ secrets.SSH }}
    - run: ssh -T git@github.com || true
  macos:
    runs-on: macos-latest
    steps:
    - uses: LuisEnMarroquin/git-login-action@v1.0
      with:
        SSHKEY: ${{ secrets.SSH }}
    - run: ssh -T git@github.com || true
  windows:
    runs-on: windows-latest
    steps:
    - uses: LuisEnMarroquin/git-login-action@v1.0
      with:
        SSHKEY: ${{ secrets.SSH }}
    - run: ssh -T git@github.com || true
