name: Windows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.5
        with:
          SSHKEY: ${{ secrets.SSH_GITHUB }}
      - run: ssh -T git@github.com || true
